# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'test.ui'
#
# Created by: PyQt5 UI code generator 5.8.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(783, 742)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.viewRowsButton = QtWidgets.QPushButton(self.centralwidget)
        self.viewRowsButton.setGeometry(QtCore.QRect(610, 350, 131, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.viewRowsButton.setFont(font)
        self.viewRowsButton.setStyleSheet("background: rgb(170, 255, 255);")
        self.viewRowsButton.setCheckable(False)
        self.viewRowsButton.setObjectName("viewRowsButton")
        self.spinBoxPartners = QtWidgets.QSpinBox(self.centralwidget)
        self.spinBoxPartners.setGeometry(QtCore.QRect(560, 350, 42, 31))
        self.spinBoxPartners.setObjectName("spinBoxPartners")
        self.tabWidgetAlls = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidgetAlls.setGeometry(QtCore.QRect(30, 10, 711, 311))
        self.tabWidgetAlls.setObjectName("tabWidgetAlls")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.tableWidgetPartners = QtWidgets.QTableWidget(self.tab)
        self.tableWidgetPartners.setGeometry(QtCore.QRect(0, 0, 711, 311))
        self.tableWidgetPartners.setObjectName("tableWidgetPartners")
        self.tableWidgetPartners.setColumnCount(3)
        self.tableWidgetPartners.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetPartners.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetPartners.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetPartners.setHorizontalHeaderItem(2, item)
        self.tabWidgetAlls.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.tableWidgetTerminals = QtWidgets.QTableWidget(self.tab_2)
        self.tableWidgetTerminals.setGeometry(QtCore.QRect(0, 0, 711, 311))
        self.tableWidgetTerminals.setObjectName("tableWidgetTerminals")
        self.tableWidgetTerminals.setColumnCount(4)
        self.tableWidgetTerminals.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetTerminals.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetTerminals.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetTerminals.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetTerminals.setHorizontalHeaderItem(3, item)
        self.tabWidgetAlls.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.tableWidgetTransactions = QtWidgets.QTableWidget(self.tab_3)
        self.tableWidgetTransactions.setGeometry(QtCore.QRect(0, 0, 711, 311))
        self.tableWidgetTransactions.setObjectName("tableWidgetTransactions")
        self.tableWidgetTransactions.setColumnCount(6)
        self.tableWidgetTransactions.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetTransactions.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetTransactions.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetTransactions.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetTransactions.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetTransactions.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetTransactions.setHorizontalHeaderItem(5, item)
        self.tabWidgetAlls.addTab(self.tab_3, "")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(30, 410, 711, 131))
        self.tabWidget.setObjectName("tabWidget")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.pushButtonAddPartner = QtWidgets.QPushButton(self.tab_4)
        self.pushButtonAddPartner.setGeometry(QtCore.QRect(580, 40, 81, 31))
        self.pushButtonAddPartner.setStyleSheet("background: rgb(255, 255, 127);")
        self.pushButtonAddPartner.setObjectName("pushButtonAddPartner")
        self.lineEditPartnerTitle = QtWidgets.QLineEdit(self.tab_4)
        self.lineEditPartnerTitle.setGeometry(QtCore.QRect(40, 40, 211, 31))
        self.lineEditPartnerTitle.setObjectName("lineEditPartnerTitle")
        self.lineEditPartnerComment = QtWidgets.QLineEdit(self.tab_4)
        self.lineEditPartnerComment.setGeometry(QtCore.QRect(260, 40, 311, 31))
        self.lineEditPartnerComment.setObjectName("lineEditPartnerComment")
        self.label_5 = QtWidgets.QLabel(self.tab_4)
        self.label_5.setGeometry(QtCore.QRect(260, 20, 71, 16))
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.tab_4)
        self.label_6.setGeometry(QtCore.QRect(40, 20, 61, 16))
        self.label_6.setObjectName("label_6")
        self.tabWidget.addTab(self.tab_4, "")
        self.tab_5 = QtWidgets.QWidget()
        self.tab_5.setObjectName("tab_5")
        self.lineEditTerminalTitle = QtWidgets.QLineEdit(self.tab_5)
        self.lineEditTerminalTitle.setGeometry(QtCore.QRect(40, 40, 211, 31))
        self.lineEditTerminalTitle.setObjectName("lineEditTerminalTitle")
        self.pushButtonAddTerminal = QtWidgets.QPushButton(self.tab_5)
        self.pushButtonAddTerminal.setGeometry(QtCore.QRect(580, 40, 81, 31))
        self.pushButtonAddTerminal.setObjectName("pushButtonAddTerminal")
        self.label = QtWidgets.QLabel(self.tab_5)
        self.label.setGeometry(QtCore.QRect(40, 20, 61, 16))
        self.label.setObjectName("label")
        self.lineEditTerminalConfig = QtWidgets.QLineEdit(self.tab_5)
        self.lineEditTerminalConfig.setGeometry(QtCore.QRect(260, 40, 311, 31))
        self.lineEditTerminalConfig.setObjectName("lineEditTerminalConfig")
        self.label_2 = QtWidgets.QLabel(self.tab_5)
        self.label_2.setGeometry(QtCore.QRect(260, 20, 71, 16))
        self.label_2.setObjectName("label_2")
        self.tabWidget.addTab(self.tab_5, "")
        self.pushButtonEditRow = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtonEditRow.setGeometry(QtCore.QRect(454, 350, 91, 31))
        self.pushButtonEditRow.setStyleSheet("background: rgb(85, 255, 127);")
        self.pushButtonEditRow.setObjectName("pushButtonEditRow")
        self.pushButtonDeleteRow = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtonDeleteRow.setGeometry(QtCore.QRect(350, 350, 91, 31))
        self.pushButtonDeleteRow.setStyleSheet("background: rgb(255, 0, 0);\n"
"color: #ffffff;")
        self.pushButtonDeleteRow.setObjectName("pushButtonDeleteRow")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 783, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidgetAlls.setCurrentIndex(0)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.viewRowsButton.setText(_translate("MainWindow", "View"))
        item = self.tableWidgetPartners.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "ID"))
        item = self.tableWidgetPartners.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Title"))
        item = self.tableWidgetPartners.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Comment"))
        self.tabWidgetAlls.setTabText(self.tabWidgetAlls.indexOf(self.tab), _translate("MainWindow", "Partners"))
        item = self.tableWidgetTerminals.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "ID"))
        item = self.tableWidgetTerminals.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Title"))
        item = self.tableWidgetTerminals.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Configuration"))
        item = self.tableWidgetTerminals.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Comment"))
        self.tabWidgetAlls.setTabText(self.tabWidgetAlls.indexOf(self.tab_2), _translate("MainWindow", "Terminals"))
        item = self.tableWidgetTransactions.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "ID"))
        item = self.tableWidgetTransactions.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Date"))
        item = self.tableWidgetTransactions.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Terminal"))
        item = self.tableWidgetTransactions.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Transaction ID"))
        item = self.tableWidgetTransactions.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Partner"))
        item = self.tableWidgetTransactions.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "Payment"))
        self.tabWidgetAlls.setTabText(self.tabWidgetAlls.indexOf(self.tab_3), _translate("MainWindow", "Transactions"))
        self.pushButtonAddPartner.setText(_translate("MainWindow", "Add"))
        self.label_5.setText(_translate("MainWindow", "Comment"))
        self.label_6.setText(_translate("MainWindow", "Title partner"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("MainWindow", "Partners"))
        self.pushButtonAddTerminal.setText(_translate("MainWindow", "Add"))
        self.label.setText(_translate("MainWindow", "Title terminal"))
        self.label_2.setText(_translate("MainWindow", "Configuration"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_5), _translate("MainWindow", "Terminals"))
        self.pushButtonEditRow.setText(_translate("MainWindow", "Edit"))
        self.pushButtonDeleteRow.setText(_translate("MainWindow", "Delete"))

