# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'test.ui'
#
# Created by: PyQt5 UI code generator 5.8.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.viewPartnersBtn = QtWidgets.QPushButton(self.centralwidget)
        self.viewPartnersBtn.setGeometry(QtCore.QRect(610, 350, 131, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.viewPartnersBtn.setFont(font)
        self.viewPartnersBtn.setCheckable(False)
        self.viewPartnersBtn.setObjectName("viewPartnersBtn")
        self.spinBoxPartners = QtWidgets.QSpinBox(self.centralwidget)
        self.spinBoxPartners.setGeometry(QtCore.QRect(560, 350, 42, 31))
        self.spinBoxPartners.setObjectName("spinBoxPartners")
        self.tabWidgetAlls = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidgetAlls.setGeometry(QtCore.QRect(30, 10, 711, 311))
        self.tabWidgetAlls.setObjectName("tabWidgetAlls")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.tableWidgetPartners = QtWidgets.QTableWidget(self.tab)
        self.tableWidgetPartners.setGeometry(QtCore.QRect(0, 0, 711, 311))
        self.tableWidgetPartners.setObjectName("tableWidgetPartners")
        self.tableWidgetPartners.setColumnCount(3)
        self.tableWidgetPartners.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetPartners.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetPartners.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetPartners.setHorizontalHeaderItem(2, item)
        self.tabWidgetAlls.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.tableWidgetTerminals = QtWidgets.QTableWidget(self.tab_2)
        self.tableWidgetTerminals.setGeometry(QtCore.QRect(0, 0, 711, 311))
        self.tableWidgetTerminals.setObjectName("tableWidgetTerminals")
        self.tableWidgetTerminals.setColumnCount(4)
        self.tableWidgetTerminals.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetTerminals.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetTerminals.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetTerminals.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetTerminals.setHorizontalHeaderItem(3, item)
        self.tabWidgetAlls.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.tableWidgetTransactions = QtWidgets.QTableWidget(self.tab_3)
        self.tableWidgetTransactions.setGeometry(QtCore.QRect(0, 0, 711, 311))
        self.tableWidgetTransactions.setObjectName("tableWidgetTransactions")
        self.tableWidgetTransactions.setColumnCount(6)
        self.tableWidgetTransactions.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetTransactions.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetTransactions.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetTransactions.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetTransactions.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetTransactions.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetTransactions.setHorizontalHeaderItem(5, item)
        self.tabWidgetAlls.addTab(self.tab_3, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidgetAlls.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.viewPartnersBtn.setText(_translate("MainWindow", "View"))
        item = self.tableWidgetPartners.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "ID"))
        item = self.tableWidgetPartners.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Title"))
        item = self.tableWidgetPartners.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Comment"))
        self.tabWidgetAlls.setTabText(self.tabWidgetAlls.indexOf(self.tab), _translate("MainWindow", "Partners"))
        item = self.tableWidgetTerminals.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "ID"))
        item = self.tableWidgetTerminals.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Title"))
        item = self.tableWidgetTerminals.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Configuration"))
        item = self.tableWidgetTerminals.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Comment"))
        self.tabWidgetAlls.setTabText(self.tabWidgetAlls.indexOf(self.tab_2), _translate("MainWindow", "Terminals"))
        item = self.tableWidgetTransactions.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "ID"))
        item = self.tableWidgetTransactions.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Date"))
        item = self.tableWidgetTransactions.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Terminal"))
        item = self.tableWidgetTransactions.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Transaction ID"))
        item = self.tableWidgetTransactions.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Partner"))
        item = self.tableWidgetTransactions.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "Payment"))
        self.tabWidgetAlls.setTabText(self.tabWidgetAlls.indexOf(self.tab_3), _translate("MainWindow", "Transactions"))

